//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsRespons
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Status { get; set; }
        public string MessageId { get; set; }
        public string Cost { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
