//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public System.Guid Id { get; set; }
        public string ModelName { get; set; }
        public string ModelYear { get; set; }
        public string PlateNumber { get; set; }
        public int MakeId { get; set; }
        public int Capacity { get; set; }
        public string Owner { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public long Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual VehicleMake VehicleMake { get; set; }
    }
}
